#!/bin/bash
# ci_post_clone.sh — Xcode Cloud Post-Clone Script
# Erstellt App/Secrets.xcconfig aus Xcode Cloud Environment Variable

set -e

echo "🔧 ci_post_clone: Erstelle Secrets.xcconfig..."

SECRETS_FILE="$CI_PRIMARY_REPOSITORY_PATH/App/Secrets.xcconfig"

if [ -n "$AI_PROXY_SECRET" ]; then
    echo "// Auto-generated by Xcode Cloud ci_post_clone.sh" > "$SECRETS_FILE"
    echo "AI_PROXY_SECRET = $AI_PROXY_SECRET" >> "$SECRETS_FILE"
    echo "✅ Secrets.xcconfig erstellt (mit Secret aus Environment)"
else
    echo "// Auto-generated by Xcode Cloud ci_post_clone.sh (dummy)" > "$SECRETS_FILE"
    echo "AI_PROXY_SECRET = " >> "$SECRETS_FILE"
    echo "⚠️ Secrets.xcconfig erstellt (OHNE Secret — KI-Features deaktiviert)"
fi
